version: '3.1'

services: 
  mysql: 
    image: satyawan/mysql-custom
    environment: 
      MYSQL_ROOT_PASSWORD: eyMgezuZYC4NL7XS 
      MYSQL_DATABASE: dbkuasai
      MYSQL_USER: cilsykuasaiuser
      MYSQL_PASSWORD: cilsykuasaipassword
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - int_net
  pma:
    image: satyawan/pma-custom
    links:
      - mysql:db
    networks:
      - proxy_net
      - int_net
  web:
    #build:
      #context: .
      #dockerfile: web.Dockerfile
    image: satyawan/web-custom 
    volumes:
      - ./file-web:/var/www/html/
        #- ./file-web:/usr/local/apache2/htdocs/
    networks: 
      - proxy_net
      - int_net
  proxy:
    #build: 
      #context: .
      #dockerfile: nginx.Dockerfile
    image: satyawan/pma-custom
      ports: 
      - '80:80'
    networks:
      - ext_net
      - proxy_net
volumes:
  mysql-data:
networks:
  int_net:
  proxy_net:
  ext_net: