version: '3.1'

services: 
  mysql: 
    image: satyawan/mysql-custom:5.7
    environment: 
      MYSQL_ROOT_PASSWORD: eyMgezuZYC4NL7XS 
      MYSQL_DATABASE: dbkuasai
      MYSQL_USER: cilsykuasaiuser
      MYSQL_PASSWORD: cilsykuasaipassword
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - int_net

  pma:
    image: satyawan/pma-custom:1.0
    links:
      - mysql:db
    depends_on: 
      - mysql 
    networks:
      - proxy_net
      - int_net

  web:
    image: satyawan/web-custom:1.0
    depends_on: 
      - mysql 
    volumes:
      - ./file-web:/var/www/html/
    networks: 
      - proxy_net
      - int_net

  proxy:
    image: satyawan/proxy-custom:1.0
    ports: 
      - '80:80'
    networks:
      - ext_net
      - proxy_net

volumes:
  mysql-data:
    driver: rexray/dobs
    driver_opts: 
      size: 2

networks:
  int_net:
  proxy_net:
  ext_net:
