version: '3.1'

services: 
  mysql: 
    image: mysql:5.7
    environment: 
      MYSQL_ROOT_PASSWORD: eyMgezuZYC4NL7XS 
      MYSQL_DATABASE: dbkuasai
      MYSQL_USER: cilsykuasaiuser
      MYSQL_PASSWORD: cilsykuasaipassword
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - int_net
  pma:
    image: phpmyadmin:5
    networks:
      - proxy_net
      - int_net
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    #image: satyawan/web-custom
    depends_on: 
      - mysql 
    restart: always
    volumes:
      - ./file-web:/var/www/html/
    networks: 
      - proxy_net
      - int_net
  proxy:
    build: 
      context: .
      dockerfile: nginx.Dockerfile
    #image: satyawan/proxy-custom
    ports: 
      - '80:80'
    networks:
      - ext_net
      - proxy_net

volumes:
  mysql-data:

networks:
  int_net:
  proxy_net:
  ext_net: